import { appSchema, tableSchema } from "@nozbe/watermelondb";

export const schema = appSchema({
  version: 27,
  tables: [
    tableSchema({
      name: "travels",
      columns: [
        { name: "title", type: "string" },
        { name: "description", type: "string", isOptional: true },
        { name: "destination", type: "string", isOptional: true },
        { name: "destination_data", type: "string", isOptional: true }, // JSON string
        { name: "start_or_departure_date", type: "number", isOptional: true }, // Date as timestamp
        { name: "end_or_return_date", type: "number", isOptional: true },
        { name: "status", type: "number", isOptional: true },
        { name: "budget", type: "string", isOptional: true },
        { name: "notes", type: "string", isOptional: true },
        { name: "is_offline", type: "boolean" },
        { name: "is_archived", type: "boolean", isOptional: true },
        { name: "type", type: "number", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "itinerary_sections",
      columns: [
        { name: "travel_id", type: "string", isIndexed: true },
        { name: "title", type: "string" },
        { name: "description", type: "string", isOptional: true },
        { name: "destination", type: "string", isOptional: true },
        { name: "start_date", type: "number", isOptional: true },
        { name: "end_date", type: "number", isOptional: true },
        { name: "budget", type: "string", isOptional: true },
        { name: "notes", type: "string", isOptional: true },
        { name: "is_offline", type: "boolean" },
        { name: "sort_order", type: "string" },
        { name: "is_default_section", type: "boolean" },
        { name: "is_collapsed", type: "boolean" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "itinerary_activities",
      columns: [
        { name: "section_id", type: "string", isIndexed: true },
        { name: "title", type: "string" },
        { name: "description", type: "string", isOptional: true },
        { name: "destination", type: "string", isOptional: true },
        { name: "destination_data", type: "string", isOptional: true }, // JSON string
        { name: "start_date", type: "number", isOptional: true },
        { name: "end_date", type: "number", isOptional: true },
        { name: "budget", type: "string", isOptional: true },
        { name: "notes", type: "string", isOptional: true },
        { name: "is_offline", type: "boolean" },
        { name: "sort_order", type: "string" },
        { name: "type", type: "number", isOptional: true },
        { name: "secondary_type", type: "string", isOptional: true }, // JSON string
        { name: "images", type: "string", isOptional: true }, // JSON string
        { name: "is_done", type: "boolean" },
        { name: "attachments", type: "string", isOptional: true }, // JSON string
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "itinerary_expenses",
      columns: [
        { name: "travel_id", type: "string", isIndexed: true },
        { name: "activity_id", type: "string", isOptional: true, isIndexed: true },
        { name: "member_id", type: "string", isOptional: true, isIndexed: true },
        { name: "title", type: "string" },
        { name: "amount", type: "number" },
        { name: "date_time", type: "number" },
        { name: "currency", type: "string", isOptional: true },
        { name: "category", type: "string", isOptional: true },
        { name: "expense_category", type: "number", isOptional: true },
        { name: "user_id", type: "string", isOptional: true },
        { name: "notes", type: "string", isOptional: true },
        { name: "is_offline", type: "boolean" },
        { name: "is_include_in_bill", type: "boolean" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "itinerary_notes",
      columns: [
        { name: "travel_id", type: "string", isIndexed: true },
        { name: "activity_id", type: "string", isOptional: true, isIndexed: true },
        { name: "title", type: "string" },
        { name: "content", type: "string", isOptional: true },
        { name: "images", type: "string", isOptional: true }, // JSON array of URIs
        { name: "user_id", type: "string", isOptional: true },
        { name: "is_offline", type: "boolean" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "checklist_groups",
      columns: [
        { name: "travel_id", type: "string", isIndexed: true },
        { name: "title", type: "string" },
        { name: "description", type: "string", isOptional: true },
        { name: "sort_order", type: "string" },
        { name: "user_id", type: "string", isOptional: true },
        { name: "is_offline", type: "boolean" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "checklist_items",
      columns: [
        { name: "travel_id", type: "string", isIndexed: true },
        { name: "activity_id", type: "string", isOptional: true, isIndexed: true },
        { name: "checklist_group_id", type: "string", isOptional: true, isIndexed: true },
        { name: "title", type: "string" },
        { name: "description", type: "string", isOptional: true },
        { name: "sort_order", type: "string" },
        { name: "is_done", type: "boolean" },
        { name: "user_id", type: "string", isOptional: true },
        { name: "checked_by", type: "string", isOptional: true },
        { name: "checked_at", type: "number", isOptional: true },
        { name: "uncheck_by", type: "string", isOptional: true },
        { name: "uncheck_at", type: "number", isOptional: true },
        { name: "is_offline", type: "boolean" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "user_profiles",
      columns: [
        { name: "username", type: "string", isOptional: true },
        { name: "nickname", type: "string", isOptional: true },
        { name: "travel_style", type: "string", isOptional: true },
        { name: "email", type: "string", isOptional: true },
        { name: "avatar_url", type: "string", isOptional: true },
        { name: "default_currency", type: "string", isOptional: true },
        { name: "default_country", type: "string", isOptional: true },
        { name: "account_type", type: "number" },
        { name: "notifications_enabled", type: "boolean", isOptional: true },
        { name: "notify_days_before_trip", type: "number", isOptional: true },
        { name: "notify_hours_before_activity", type: "number", isOptional: true },
        { name: "backup_frequency", type: "string", isOptional: true },
        { name: "backup_location", type: "string", isOptional: true },
        { name: "backup_auto_enabled", type: "boolean", isOptional: true },
        { name: "last_backed_up_at", type: "number", isOptional: true },
        { name: "google_drive_account", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "error_logs",
      columns: [
        // Categorization
        { name: "category", type: "string", isIndexed: true }, // 'API' | 'Database' | 'UI' | 'Navigation' | 'Service' | 'Unknown'
        { name: "severity", type: "string", isIndexed: true }, // 'low' | 'medium' | 'high' | 'critical'
        // Error identity
        { name: "error_code", type: "string", isOptional: true },   // e.g. 'ERR_NETWORK', 'ERR_DB_WRITE'
        { name: "message", type: "string" },                         // error.message
        { name: "stack_trace", type: "string", isOptional: true },   // error.stack (truncated)
        // Context
        { name: "screen", type: "string", isOptional: true },        // screen/component where it happened
        { name: "action", type: "string", isOptional: true },        // what user action triggered it
        { name: "context_data", type: "string", isOptional: true },  // JSON: relevant IDs, params, etc.
        // App state
        { name: "app_version", type: "string", isOptional: true },
        { name: "platform", type: "string", isOptional: true },      // 'ios' | 'android'
        { name: "device_info", type: "string", isOptional: true },   // JSON: model, OS version
        // Status
        { name: "is_resolved", type: "boolean" },
        { name: "resolved_note", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "trip_members",
      columns: [
        { name: "travel_id", type: "string", isIndexed: true },
        { name: "name", type: "string" },
        { name: "description", type: "string", isOptional: true },
        { name: "email", type: "string", isOptional: true },
        { name: "is_offline", type: "boolean" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "member_split_bills",
      columns: [
        { name: "travel_id", type: "string", isIndexed: true },
        { name: "member_id", type: "string", isIndexed: true },
        { name: "owes_amount", type: "number" },
        { name: "percentage_share", type: "number" },
        { name: "is_paid", type: "boolean" },
        { name: "payment_type", type: "string", isOptional: true },
        { name: "paid_date", type: "number", isOptional: true },
        { name: "notes", type: "string", isOptional: true },
        { name: "is_offline", type: "boolean" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "flight_details",
      columns: [
        { name: "activity_id", type: "string", isIndexed: true },
        { name: "departure_airport", type: "string" },
        { name: "arrival_airport", type: "string" },
        { name: "departure_date", type: "number" },
        { name: "arrival_date", type: "number", isOptional: true },
        { name: "flight_number", type: "string", isOptional: true },
        { name: "airline", type: "string", isOptional: true },
        { name: "gate", type: "string", isOptional: true },
        { name: "terminal", type: "string", isOptional: true },
        { name: "seat_number", type: "string", isOptional: true },
        { name: "booking_reference", type: "string", isOptional: true },
        { name: "price", type: "number", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "accomodation_details",
      columns: [
        { name: "activity_id", type: "string", isIndexed: true },
        { name: "accomodation_name", type: "string" },
        { name: "address", type: "string", isOptional: true },
        { name: "checkin_date_time", type: "number" },
        { name: "checkout_date_time", type: "number", isOptional: true },
        { name: "website_address", type: "string", isOptional: true },
        { name: "booking_reference", type: "string", isOptional: true },
        { name: "booking_status", type: "string", isOptional: true },
        { name: "contact_number", type: "string", isOptional: true },
        { name: "email_address", type: "string", isOptional: true },
        { name: "contact_name", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "sightseeing_details",
      columns: [
        { name: "activity_id", type: "string", isIndexed: true },
        { name: "attraction_name", type: "string" },
        { name: "address", type: "string", isOptional: true },
        { name: "entry_fee", type: "string", isOptional: true },
        { name: "website_address", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "hike_or_camp_details",
      columns: [
        { name: "activity_id", type: "string", isIndexed: true },
        { name: "trail_or_site_name", type: "string" },
        { name: "address", type: "string", isOptional: true },
        { name: "sub_type", type: "string", isOptional: true },
        { name: "estimated_distance_km", type: "string", isOptional: true },
        { name: "campsite_name", type: "string", isOptional: true },
        { name: "permit_required", type: "boolean", isOptional: true },
        { name: "contact_person", type: "string", isOptional: true },
        { name: "contact_number", type: "string", isOptional: true },
        { name: "website_address", type: "string", isOptional: true },
        { name: "reservation_link", type: "string", isOptional: true },
        { name: "checkin_date_time", type: "number", isOptional: true },
        { name: "checkout_date_time", type: "number", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "cafe_restaurant_details",
      columns: [
        { name: "activity_id", type: "string", isIndexed: true },
        { name: "restaurant_name", type: "string" },
        { name: "address", type: "string", isOptional: true },
        { name: "cuisine", type: "string", isOptional: true },
        { name: "price_range", type: "string", isOptional: true },
        { name: "reservation_link", type: "string", isOptional: true },
        { name: "website_address", type: "string", isOptional: true },
        { name: "contact_number", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "nature_details",
      columns: [
        { name: "activity_id", type: "string", isIndexed: true },
        { name: "spot_name", type: "string" },
        { name: "address", type: "string", isOptional: true },
        { name: "sub_type", type: "string", isOptional: true },
        { name: "entry_fee", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "shopping_details",
      columns: [
        { name: "activity_id", type: "string", isIndexed: true },
        { name: "venue_name", type: "string" },
        { name: "address", type: "string", isOptional: true },
        { name: "sub_type", type: "string", isOptional: true },
        { name: "website_address", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "entertainment_details",
      columns: [
        { name: "activity_id", type: "string", isIndexed: true },
        { name: "venue_name", type: "string" },
        { name: "address", type: "string", isOptional: true },
        { name: "sub_type", type: "string", isOptional: true },
        { name: "website_address", type: "string", isOptional: true },
        { name: "ticket_price", type: "string", isOptional: true },
        { name: "booking_reference", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "transportation_details",
      columns: [
        { name: "activity_id", type: "string", isIndexed: true },
        { name: "mode", type: "string", isOptional: true },
        { name: "operator_provider", type: "string", isOptional: true },
        { name: "pickup_location", type: "string", isOptional: true },
        { name: "dropoff_location", type: "string", isOptional: true },
        { name: "booking_reference", type: "string", isOptional: true },
        { name: "price", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "walk_details",
      columns: [
        { name: "activity_id", type: "string", isIndexed: true },
        { name: "route_name", type: "string", isOptional: true },
        { name: "estimated_distance_km", type: "string", isOptional: true },
        { name: "estimated_duration", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "preparation_details",
      columns: [
        { name: "activity_id", type: "string", isIndexed: true },
        { name: "task_label", type: "string", isOptional: true },
        { name: "deadline_date_time", type: "number", isOptional: true },
        { name: "priority", type: "string", isOptional: true },
        { name: "notes", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "rest_details",
      columns: [
        { name: "activity_id", type: "string", isIndexed: true },
        { name: "rest_location_name", type: "string", isOptional: true },
        { name: "rest_location_type", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "motorcycle_ride_details",
      columns: [
        { name: "activity_id", type: "string", isIndexed: true },
        { name: "route_name", type: "string", isOptional: true },
        { name: "starting_point", type: "string", isOptional: true },
        { name: "ending_point", type: "string", isOptional: true },
        { name: "estimated_distance_km", type: "string", isOptional: true },
        { name: "road_type", type: "string", isOptional: true },
        { name: "bike_model", type: "string", isOptional: true },
        { name: "fuel_stops", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "meetup_details",
      columns: [
        { name: "activity_id", type: "string", isIndexed: true },
        { name: "venue_name", type: "string" },
        { name: "address", type: "string", isOptional: true },
        { name: "host_or_organizer", type: "string", isOptional: true },
        { name: "number_of_people", type: "string", isOptional: true },
        { name: "meetup_type", type: "string", isOptional: true },
        { name: "rsvp_link", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "ride_rental_details",
      columns: [
        { name: "activity_id", type: "string", isIndexed: true },
        { name: "provider_name", type: "string" },
        { name: "address", type: "string", isOptional: true },
        { name: "vehicle_type", type: "string", isOptional: true },
        { name: "pickup_location", type: "string", isOptional: true },
        { name: "dropoff_location", type: "string", isOptional: true },
        { name: "rental_start_date_time", type: "number", isOptional: true },
        { name: "rental_end_date_time", type: "number", isOptional: true },
        { name: "booking_reference", type: "string", isOptional: true },
        { name: "price", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "trip_settings",
      columns: [
        { name: "travel_id", type: "string", isIndexed: true },
        { name: "currency", type: "string" },
        { name: "timezone", type: "string" },
        { name: "itinerary_view", type: "string" },
        { name: "allow_item_reordering", type: "boolean" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "app_notifications",
      columns: [
        { name: "title", type: "string" },
        { name: "body", type: "string" },
        { name: "is_read", type: "boolean" },
        { name: "travel_id", type: "string", isOptional: true, isIndexed: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
  ],
});
